(function(global) {
  'use strict';

  const ARP2600_PRESETS = [
    {
      name: 'Classic Bleeps',
      bpm: 105,
      vco1Wave:   'square',
      vco2Wave:   'triangle',
      vco2Detune: 7,
      ringMod:    false,
      knobs: {
        cutoff:   0.5,
        reso:     0.45,
        envMod:   0.6,
        attack:   0.01,
        decay:    0.35,
        sustain:  0.3,
        release:  0.25,
        reverbMix: 0.3,
      },
      steps: [
        { note: 'C',  octave: 1, rest: false },
        { note: 'C',  octave: 1, rest: true  },
        { note: 'E',  octave: 1, rest: false },
        { note: 'G',  octave: 1, rest: true  },
        { note: 'A#', octave: 1, rest: false },
        { note: 'A#', octave: 1, rest: true  },
        { note: 'G',  octave: 1, rest: false },
        { note: 'E',  octave: 1, rest: false },
        { note: 'F',  octave: 1, rest: false },
        { note: 'F',  octave: 1, rest: true  },
        { note: 'A',  octave: 1, rest: false },
        { note: 'C',  octave: 1, rest: true  },
        { note: 'D',  octave: 1, rest: false },
        { note: 'D',  octave: 1, rest: true  },
        { note: 'C',  octave: 1, rest: false },
        { note: 'A',  octave: 0, rest: false },
      ],
    },
    {
      name: 'Ring Drone',
      bpm: 90,
      vco1Wave:   'sawtooth',
      vco2Wave:   'sawtooth',
      vco2Detune: 5,
      ringMod:    true,
      knobs: {
        cutoff:    0.6,
        reso:      0.3,
        envMod:    0.4,
        attack:    0.05,
        decay:     0.6,
        sustain:   0.5,
        release:   0.5,
        reverbMix: 0.4,
      },
      steps: [
        { note: 'D',  octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: false },
        { note: 'A',  octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: true  },
        { note: 'F',  octave: 0, rest: false },
        { note: 'F',  octave: 0, rest: false },
        { note: 'A',  octave: 0, rest: false },
        { note: 'C',  octave: 1, rest: true  },
        { note: 'D',  octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: true  },
        { note: 'G',  octave: 0, rest: false },
        { note: 'G',  octave: 0, rest: false },
        { note: 'A#', octave: 0, rest: false },
        { note: 'A',  octave: 0, rest: true  },
        { note: 'G',  octave: 0, rest: false },
        { note: 'F',  octave: 0, rest: false },
      ],
    },
    {
      name: 'Arp Lead',
      bpm: 125,
      vco1Wave:   'sawtooth',
      vco2Wave:   'square',
      vco2Detune: -12,
      ringMod:    false,
      knobs: {
        cutoff:    0.45,
        reso:      0.55,
        envMod:    0.7,
        attack:    0.005,
        decay:     0.2,
        sustain:   0.4,
        release:   0.2,
        reverbMix: 0.15,
      },
      steps: [
        { note: 'A',  octave: 0, rest: false },
        { note: 'C',  octave: 1, rest: false },
        { note: 'E',  octave: 1, rest: false },
        { note: 'A',  octave: 1, rest: false },
        { note: 'G',  octave: 1, rest: false },
        { note: 'E',  octave: 1, rest: false },
        { note: 'C',  octave: 1, rest: false },
        { note: 'A',  octave: 0, rest: false },
        { note: 'F',  octave: 0, rest: false },
        { note: 'A',  octave: 0, rest: false },
        { note: 'C',  octave: 1, rest: false },
        { note: 'F',  octave: 1, rest: false },
        { note: 'E',  octave: 1, rest: false },
        { note: 'D',  octave: 1, rest: false },
        { note: 'C',  octave: 1, rest: false },
        { note: 'A',  octave: 0, rest: true  },
      ],
    },
  ];

  global.ARP2600_PRESETS = ARP2600_PRESETS;

})(window);
