(function(global) {
  'use strict';

  const MS20_PRESETS = [
    {
      name: 'Acid Harsh',
      bpm: 130,
      osc1Wave: 'sawtooth',
      osc2Wave: 'square',
      osc2Detune: 0,
      knobs: {
        cutoff:   0.3,
        reso:     0.75,
        hpCutoff: 0.15,
        envMod:   0.7,
        attack:   0.005,
        decay:    0.25,
        sustain:  0.2,
        release:  0.15,
      },
      steps: [
        { note: 'A',  octave: 0, rest: false },
        { note: 'A',  octave: 0, rest: true  },
        { note: 'A',  octave: 0, rest: false },
        { note: 'C',  octave: 1, rest: false },
        { note: 'E',  octave: 1, rest: false },
        { note: 'E',  octave: 1, rest: true  },
        { note: 'D',  octave: 1, rest: false },
        { note: 'D',  octave: 1, rest: true  },
        { note: 'C',  octave: 1, rest: false },
        { note: 'A',  octave: 0, rest: false },
        { note: 'G',  octave: 0, rest: false },
        { note: 'G',  octave: 0, rest: true  },
        { note: 'F',  octave: 0, rest: false },
        { note: 'E',  octave: 0, rest: false },
        { note: 'A',  octave: 0, rest: false },
        { note: 'A',  octave: 0, rest: true  },
      ],
    },
    {
      name: 'Industrial',
      bpm: 140,
      osc1Wave: 'square',
      osc2Wave: 'square',
      osc2Detune: -7,
      knobs: {
        cutoff:   0.4,
        reso:     0.6,
        hpCutoff: 0.25,
        envMod:   0.5,
        attack:   0.01,
        decay:    0.2,
        sustain:  0.3,
        release:  0.1,
      },
      steps: [
        { note: 'D',  octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: true  },
        { note: 'D',  octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: true  },
        { note: 'F',  octave: 0, rest: false },
        { note: 'F',  octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: true  },
        { note: 'A#', octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: true  },
        { note: 'C',  octave: 0, rest: false },
        { note: 'C',  octave: 0, rest: false },
        { note: 'A#', octave: 0, rest: false },
        { note: 'A#', octave: 0, rest: true  },
        { note: 'G',  octave: 0, rest: false },
        { note: 'D',  octave: 0, rest: false },
      ],
    },
    {
      name: 'Drone Bass',
      bpm: 100,
      osc1Wave: 'sawtooth',
      osc2Wave: 'sawtooth',
      osc2Detune: 7,
      knobs: {
        cutoff:   0.6,
        reso:     0.35,
        hpCutoff: 0.05,
        envMod:   0.3,
        attack:   0.02,
        decay:    0.5,
        sustain:  0.6,
        release:  0.3,
      },
      steps: [
        { note: 'E',  octave: 0, rest: false },
        { note: 'E',  octave: 0, rest: false },
        { note: 'E',  octave: 0, rest: true  },
        { note: 'E',  octave: 0, rest: false },
        { note: 'G',  octave: 0, rest: false },
        { note: 'G',  octave: 0, rest: false },
        { note: 'G',  octave: 0, rest: true  },
        { note: 'A',  octave: 0, rest: false },
        { note: 'B',  octave: 0, rest: false },
        { note: 'B',  octave: 0, rest: false },
        { note: 'B',  octave: 0, rest: true  },
        { note: 'A',  octave: 0, rest: false },
        { note: 'G',  octave: 0, rest: false },
        { note: 'G',  octave: 0, rest: false },
        { note: 'E',  octave: 0, rest: false },
        { note: 'E',  octave: 0, rest: true  },
      ],
    },
  ];

  global.MS20_PRESETS = MS20_PRESETS;

})(window);
